PACKAGE_NAME=dpimod
PACKAGE_VERSION=0.0.1
CLEAN="make clean KVERSION=$kernelver"
MAKE[0]="make modules --debug KVERSION=$kernelver"
BUILT_MODULE_NAME[0]=dpimod
DEST_MODULE_LOCATION[0]=/updates
AUTOINSTALL=yes
